### ISSUE TITLE
Flags not implemented

### ISSUE THREAD

**Issue by aparks5** [arciisine/vscode-chronicler#2]
By the way, fantastic extension, puzzled why there aren't more users.

Repro: attempt to record screen in full quality (no encoding, would like text to remain crisp)

```
 "chronicler.recording-defaults": {
        "fps": 30,
        "countdown": 1,
        "flags": "-video_size 1920x1080 -framerate 30 -f x11grab -i :0.0 -c:v libx264 -crf 0 -preset ultrafast"
    }
```

Result: flags not applied, image still blurry

**Comment by arciisine** [comment]
Thanks for the feedback. I'll take a look at why that is the case, as those should supersede the default values.  Additionally, it seems like it would be a good idea to provide the ability to adjust quality/size accordingly.

**Comment by arciisine** [comment]
Okay, looking a little closer, most things are overridable (save for the desktop/layout pieces).  Flags is expecting an object, instead of a string, e.g.:
```json
"chronicler.recording-defaults": {
        "fps": 30,
        "countdown": 1,
        "flags": {
            "crf": 0,
        }
    }
```
Not all flags are currently overridable,  there is a bug fix for https://github.com/arciisine/screen-recorder/issues/1 that I will be releasing.  

Additionally, to support quicktime, we use the yuv420 color space which causes some of the colors to look washed out, and seem less crisp.  With the next release, this should be configurable.

Also, please take a look at https://github.com/arciisine/screen-recorder if you are looking for a simpler interface for screen recording, this is what the vscode plugin is built upon.

**Comment by arciisine** [comment]
I released with a better color profile, let me know if this looks better.

**Comment by arciisine** [comment]
Closing assuming the latest release solved the issue.
