### ISSUE TITLE
Chronicler Record With Audio silently fails

### ISSUE THREAD

**Issue by flyinbutrs** [arciisine/vscode-chronicler#21]
Hi, I really like the plugin, but I can't get it to work with audio on OSX using the brew deployed version of FFMpeg. There's a note in your readme about needing a custom build of FFMpeg on OSX, but the link is dead, and the bug is marked as closed. Not sure how to proceed. I tried turning on Debug, but I can't actually find where the logs go.

Any tips?

Thanks!

**Comment by arciisine** [comment]
Hey, thanks for the heads up, the binary can be found at: https://github.com/arciisine/vscode-chronicler/blob/master/binaries/osx/ffmpeg. I'll need to update the README, this binary may need to be updated at some point depending on any OSX changes.

**Comment by flyinbutrs** [comment]
That requires a different lib than what I've got present:

```
$ ./ffmpeg
dyld: Library not loaded: /usr/local/opt/x264/lib/libx264.155.dylib
  Referenced from: /Users/me/bin/./ffmpeg
  Reason: image not found
[1]    15681 abort      ./ffmpeg
$ ls /usr/local/opt/x264/lib/
libx264.160.dylib libx264.a         libx264.dylib     pkgconfig
```

**Comment by arciisine** [comment]
Hmm. That should be statically compiled, I'll need to look at it.  The real issue here is that audio and screen recording on ffmpeg, on OSX, is broken. Let me see if I can't recompile the binary statically.  The referenced issue https://trac.ffmpeg.org/ticket/4513 has been marked as closed and indication that the patch no longer applies to the 4.2.x build of ffmpeg.

**Comment by arciisine** [comment]
Additionally you could install libx265 via homebrew (`brew install x265`) and probably get that working as well.
